version: '3.4'

services:
  wish-me-backend:     
    build:
      context: ./wishme-dotnet/WishMe.Service
      dockerfile: Dockerfile
    environment:
      WISH_ME_HEUREKA_GALLERY_THUMBNAIL_IMAGE: "c-gallery-open__thumbnail"
      WISH_ME_HEUREKA_RECOMMENDED_OFFER: "c-offer-v3__price u-bold u-delta"
      WISH_ME_DB_CONNECTION_STRING: "Server=host.docker.internal;Database=WishMe-dev;User Id=SA;Password=Pass@word1;"
      WISH_ME_JWT_KEY: ":yFD8uJG}jq2^.~q"
    ports:
      - "8085:80"

  wish-me-swaggerui:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "3200:8080"
    environment:
      URLS: '[ { url: " http://localhost:8085/docs/v1/swagger.json", name: "WishMe Service" } ]'

  wish-me-mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      SA_PASSWORD: "Pass@word1"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
