version: '3.4'

services:
  wish-me-backend:     
    build:
      context: .
      dockerfile: wishme-dotnet/WishMe.Service/Dockerfile
    depends_on:
      - wish-me-db
    environment:     
      WISH_ME_MONGO_URL: "mongodb://host.docker.internal"
      WISH_ME_MONGO_DB_NAME: "WishMe"
      WISH_ME_JWT_KEY: ":yFD8uJG}jq2^.~q"
      WISH_ME_HEUREKA_GALLERY_THUMBNAIL_IMAGE: "c-gallery-open__thumbnail"
      WISH_ME_HEUREKA_RECOMMENDED_OFFER: "c-offer-v3__price u-bold u-delta"
      WISH_ME_HEUREKA_SEARCH_REQUEST_URL: "https://api.heureka.cz/head-gateway/search?term={0}"
    ports:
      - "8085:80"

  wish-me-swaggerui:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "3200:8080"
    environment:
      URLS: '[ { url: " http://localhost:8085/docs/v1/swagger.json", name: "WishMe Service" } ]'

  wish-me-db:
    image: mongo:latest
    volumes:
      - mongodata_volume:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_DATA_DIR: "/data/db"
    container_name: "24vs-mongodb"

volumes:
  mongodata_volume: